# Autogenerated wrapper script for wuffs_jll for aarch64-apple-darwin
export libwuffs

JLLWrappers.@generate_wrapper_header("wuffs")
JLLWrappers.@declare_library_product(libwuffs, "@rpath/libwuffs.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libwuffs,
        "lib/libwuffs.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
